### ISSUE TITLE
Some tags are always pulled

### ISSUE THREAD

**Issue by jaredoconnell** [arcalot/arcaflow-engine-deployer-docker#31]
## Describe the bug

For a reason that is not clear to me, tags that do not match the regular expression `^[a-zA-Z0-9.-]$` are always pulled.
I don't see a reason for that. No comment was left. We should remove this unless we find a valid reason.

**Comment by webbnh** [comment]
And/or we should add underscore to the list of permissible characters....  ([Ref](https://docs.docker.com/engine/reference/commandline/image_tag/#:~:text=can%20contain%20lowercase%20and%20uppercase%20letters%2C%20digits%2C%20underscores%2C%20periods%2C%20and%20hyphens))

Possibly (and this is a total guess), the reason for trying to pull the other cases is to allow the `docker` command to generate the error for us.

**Comment by webbnh** [comment]
Based on the previous reference, we might want to consider expanding the regex to
```
^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,127}$
```
That is, it starts with an alphanumeric or underscore followed by up to 127 legal characters.  That pattern won't match if the tag is too long.

**Comment by jaredoconnell** [comment]
> Based on the previous reference, we might want to consider expanding the regex to
> 
> ```
> ^[a-zA-Z0-9_][a-zA-Z0-9_.-]{0,127}$
> ```
> 
> That is, it starts with an alphanumeric or underscore followed by up to 127 legal characters. That pattern won't match if the tag is too long.

Interesting idea as to the reasoning. I'll add that comment and change the regex.
